"project_id": "demschooltools"
"preserve_hierarchy": true
"base_url": "https://api.crowdin.com"

"files": [
  {
    "source": "/conf/messages.en-US",
    "translation": "/conf/messages.%locale%"
  },
]